# Generated by Django 4.0.6 on 2022-12-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problems',
            fields=[
                ('prob_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=5000)),
                ('postedby', models.CharField(max_length=50)),
                ('location', models.CharField(default='', max_length=50)),
                ('votes', models.IntegerField()),
                ('status', models.CharField(choices=[('CC', 'CC'), ('IC', 'IC'), ('IP', 'IP')], default='CC', max_length=2)),
                ('postdate', models.DateField(blank=True, verbose_name='postdate(mm/dd/yyyy)')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='startdate(mm/dd/yyyy)')),
                ('ecompletiondate', models.DateField(blank=True, null=True, verbose_name='ecompletiondate(mm/dd/yyyy)')),
                ('acompletiondate', models.DateField(blank=True, null=True, verbose_name='acompletiondate(mm/dd/yyyy)')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfeedback', models.CharField(max_length=50000)),
                ('prob_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.problems')),
            ],
        ),
    ]
